name: Deploy Nginx Cert

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nginx
        run: |
          sudo apt-get update -y
          sudo apt install nginx/1.18.0 -y
          
      - name: Copy archives
        run: |
          cp -rv etc/nginx /etc/nginx
          cp -rv var/log/nginx /var/log/nginx

      - name: Criar o certificado a partir do Base64
        run: |
          echo "$PETMATCHING_CRT" "$CA_INTERMEDIARIA" "$ROOT_CA" | base64 --decode > /etc/nginx/ssl/petmaching.com.br.crt
          echo "$PETMATCHING_KEY" | base64 --decode > /etc/nginx/ssl/petmaching.com.br.key
        env:
          CERTIFICADO_BASE64: ${{ secrets.CERTIFICADO_BASE64 }}
          CHAVE_BASE64: ${{ secrets.CHAVE_BASE64 }}
          CA_CHAIN_BASE64: ${{ secrets.CA_CHAIN_BASE64 }}

      - name: Restart Nginx to apply new certificate
        run: sudo systemctl restart nginx

      - name: Test a certificate
        run: |
          echo -s | openssl s_client -servername petmatching.com.br -connect localhost:443 2>&1 |openssl x509 -noout -issuer -dates -subject | grep "not"
          echo -s | openssl s_client -servername petmatching.com.br -connect localhost:443 2>&1 | grep "Verify return code"
